#
#

OBJ := main.o interface.o adapters.o
OBJ += buffer.o
OBJ += link.o hwaddr_cache.o
OBJ += ipv4.o icmp.o arp.o
OBJ += ipv6.o
OBJ += firewall.o routing.o
OBJ += udp.o tcp.o
NAME := IPStack
CATEGORY := 

-include ../Makefile.tpl
