# Project: Acess GUI Window Manager

-include ../../Makefile.cfg

CPPFLAGS += -I../include

DIR := Apps/AxWin/1.0
BIN := AxWinWM
OBJ := main.o helpers.o commandline.o video.o video_text.o
OBJ += messages.o interface.o wm.o decorator.o
OBJ += image.o

-include ../../Makefile.tpl
