
include ../Makefile.cfg

ANDIR := $(ACESSDIR)/AcessNative/



all:
	$(MAKE) -C $(ANDIR)libacess-native.so_src/ all
	ln -s $(ANDIR)/libacess-native.so $(OUTPUTDIR)Libs/
#	ln -s $(ANDIR)/libacess-native.dll $(OUTPUTDIR)Libs/

install:
	@true
