#!/bin/bash
if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <image>" >&2
	exit 1
fi
IMGNAME=$1
dd if=/dev/zero of="$IMGNAME" bs=512 count=2880
mformat -i "$IMGNAME" ::/ -f 1440 -v Acess
dd if=stage1 bs=1 seek=0 count=3 "of=$IMGNAME" conv=notrunc
dd if=stage1 bs=1 skip=$((0x3E)) seek=$((0x3E)) "of=$IMGNAME" conv=notrunc
mmd -i "$IMGNAME" ::/boot
mcopy stage1 stage2 -i "$IMGNAME" ::/boot/
/bin/echo -ne '\x23' | dd seek=$((0x44)) bs=1 count=1 "of=$IMGNAME" conv=notrunc
mcopy menu.lst -i "$IMGNAME" ::/boot/
