# Acess2 BSD "resolv" library
# Makefile

-include ../Makefile.cfg

CPPFLAGS += 
CFLAGS   += -Wextra
ASFLAGS  +=
LDFLAGS  += 
LIBS     += -lnet -lpsocket

OBJ  = resolv.o
BIN = libresolv.so

include ../Makefile.tpl

