#
# Acess2 Build Configuration
#

CC = gcc
LD = ld
AS = nasm
OBJDUMP = objdump
RM = @rm -f
STRIP = strip
MKDIR = mkdir
RMDIR = rm -rf
lCP = cp
xCP = mcopy -D o
xMKDIR = mmd
xRMDIR = mdeltree
xRM = mdel

ifeq ($(ARCH),)
	ARCH = i386
endif
ifeq ($(ARCHDIR),)
	ARCHDIR = x86
endif

FILESYSTEMS = fat
DRIVERS = ata_x86
MODULES = FS_Ext2 FDD NE2000 BochsGA IPStack
DYNMODS = USB
# UDI

#DISTROOT = /mnt/AcessHDD/Acess2
#DISTROOT = ~/Projects/Acess2/Filesystem
DISTROOT = a:/Acess2
ACESSDIR = /home/tpg/Projects/Acess2
