
TRIPLET = x86_64-pc-acess2
AS = nasm

KERNEL_CFLAGS := -mcmodel=kernel -nostdlib -mno-red-zone -Wall -mno-sse
DYNMOD_CFLAGS := -mcmodel=small -fPIC -mno-red-zone -mno-sse

ARCHDIR = x86_64

ASFLAGS = -felf64

