# Acess 2 - AxWin GUI Library
#

include ../../../Libraries/Makefile.cfg

CPPFLAGS += -I ../include/
CFLAGS   += -Wall
LDFLAGS  += -lc -soname libaxwin3.so

OBJ = main.o msg.o wm.o r_widget.o r_menu.o
BIN = libaxwin3.so

include ../../../Libraries/Makefile.tpl
