
#define _exit	acess__exit
#define _SysClone	acess__SysClone
#define _SysKill	acess__SysKill
#define _SysWaitEvent	acess__SysWaitEvent
#define _SysWaitTID	acess__SysWaitTID
#define gettid	acess_gettid
#define _SysGetPID	acess__SysGetPID
#define _SysGetUID	acess__SysGetUID
#define _SysGetGID	acess__SysGetGID
#define setuid	acess_setuid
#define setgid	acess_setgid
#define _SysSetName	acess__SysSetName
#define _SysGetName	acess__SysGetName
#define _SysTimestamp	acess__SysTimestamp
#define _SysSetPri	acess__SysSetPri
#define _SysSendMessage	acess__SysSendMessage
#define _SysGetMessage	acess__SysGetMessage
#define _SysSpawn	acess__SysSpawn
#define _SysExecVE	acess__SysExecVE
#define SysLoadBin	acess_SysLoadBin
#define _SysUnloadBin	acess__SysUnloadBin
#define _SysSetFaultHandler	acess__SysSetFaultHandler
#define _SysDebug	acess__SysDebug
#define _SysGetPhys	acess__SysGetPhys
#define _SysAllocate	acess__SysAllocate
#define _SysSetMemFlags	acess__SysSetMemFlags
#define _SysOpen	acess__SysOpen
#define _SysOpenChild	acess__SysOpenChild
#define _SysReopen	acess__SysReopen
#define _SysCopyFD	acess__SysCopyFD
#define _SysFDFlags	acess__SysFDFlags
#define _SysClose	acess__SysClose
#define _SysRead	acess__SysRead
#define _SysWrite	acess__SysWrite
#define _SysSeek	acess__SysSeek
#define _SysTell	acess__SysTell
#define _SysFInfo	acess__SysFInfo
#define _SysReadDir	acess__SysReadDir
#define _SysGetACL	acess__SysGetACL
#define _SysChdir	acess__SysChdir
#define _SysIOCtl	acess__SysIOCtl
#define _SysMount	acess__SysMount
#define _SysSelect	acess__SysSelect
#define _SysMkDir	acess__SysMkDir
#define _SysUnlink	acess__SysUnlink

#define _errno	acess__errno
