# Acess 2 - POSIX Sockets

include ../Makefile.cfg

CPPFLAGS +=
CFLAGS   += -Wall
LDFLAGS  += -lc -soname libpsocket.so

OBJ = main.o getaddrinfo.o socket.o
BIN = libpsocket.so

include ../Makefile.tpl
