# Acess 2 - AxWin GUI Library
#

include ../Makefile.cfg

CPPFLAGS +=
CFLAGS   += -Wall
LDFLAGS  += -lc -soname libaxwin3.so

OBJ = main.o msg.o r_widget.o
BIN = libaxwin3.so

include ../Makefile.tpl
