# Acess 2 - Networking Helpers

include ../Makefile.cfg

CPPFLAGS +=
CFLAGS   += -Wall
LDFLAGS  += -lc -soname libnet.so

OBJ = main.o address.o socket.o dns.o
BIN = libnet.so

include ../Makefile.tpl
