#
# Acess2 C Library (Math)
# - By John Hodge (thePowersGang)
#

-include ../Makefile.cfg

CPPFLAGS += 
CFLAGS   += -Werror -Wextra
ASFLAGS  +=
LDFLAGS  += 

OBJ  = stub.o pow.o
BIN := libm.so

include ../Makefile.tpl

