# Project: Acess Network Tester

-include ../Makefile.cfg

CPPFLAGS += 
CFLAGS   += -Wall -fno-builtin -fno-stack-protector
LDFLAGS  += 

BIN = writetest
OBJ = main.o

include ../Makefile.tpl
